### ISSUE TITLE
sp800_90b_compression.py   report  IndexError: list index out of range

### ISSUE THREAD

**Issue by yuyinw** [dj-on-github/SP800_90b_tests#17]
hello  ，whe  the samble  is   length   is  smaller,  i use cpu jitter  collect  480 byte(3840 bit), it report error

Traceback (most recent call last):
  File "sp800_90b_tests.py", line 210, in <module>
    (iid_assumption,T,min_entropy) = func(bits,symbol_length, verbose=verbose)
  File "F:\code\90b\SP800_90b_tests-master\sp800_90b_compression.py", line 65, in compression
    dictionary[s_prime[i]]=i
IndexError: list index out of range

**Comment by dj-on-github** [comment]
Can you send me the file?
